build "core test/ptcp_test lib/vfs_ptcp"
create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init \
                  [depot_user]/src/libc

install_config {
<config verbose="yes" prio_levels="2">
    <parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>

    <default-route>
        <any-service> <parent/> <any-child/> </any-service>
    </default-route>
    
    <default caps="100"/>

    <start name="vfs">
        <resource name="RAM" quantum="10M"/>
    </start>

    <start name="ptcp_test" caps="120" priority="-1">
        <resource name="RAM" quantum="10M"/>
        <route>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
        <config  verbose="yes" ld_verbose="yes" >
			<vfs>
				<dir name="dev">    <log/>             </dir>
				<dir name="socket"> <ptcp ass="12"/> </dir>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" socket="/socket"/>
		</config>
    </start>

</config>
}
build_boot_image {vfs_ptcp.lib.so ptcp_test }
