version: "3.9"
services: 
  genode:
    #image: sgmakarov/genode-toolchain:prebuilt
    image: mexator/genode-dev:latest
    volumes: 
      - ./genode:/genode
      - ./root:/root
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    cap_add: 
      - NET_ADMIN
    devices:
     - /dev/net/tun:/dev/net/tun
